server:
  port: 8099

logging:
  level:
    sch.hunnu.dao: DEBUG
    
spring:
    datasource:
        
        url: jdbc:mysql://127.0.0.1:3306/dbgirl
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    thymeleaf:
           #关闭缓存 可以实现及时刷新 ，但是上线应该改为true
            cache: false
            #开启模板 不为true 访问不到
            enabled: true         
        #前缀 默认为 classpath:/templates/  
            prefix: classpath:/templates/   
            suffix: .html
            mode: HTML5
            encoding: UTF-8
            servlet:
              content-type: text/html; charset=utf-8
      
#开启热部署
    devtools:
      restart:
        enabled: true
      
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: sch.hunnu.entity  # 注意：对应实体类的路径
  #开启二级缓存
  configuration:
    cache-enabled: true