server:
  port: 8088
#  servlet:
#    session:
#      timeout: 3600




spring:
  application:
    name: WebSocketServer


  datasource:

    url: jdbc:oracle:thin:@//127.0.0.1:1521/ORCL
    #jdbc:mysql://127.0.0.1:3306/char
    username: lht
    password: Lht123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    #不缓存即修改就 生效
    cache: false
    #开启MVC
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    #设置页面内的字符集
    encoding: UTF-8
    #设置http字符集
    servlet:
      content-type: text/html; charset=utf-8

#打印sql
logging:
  level:
    sch.hunnu.dao: DEBUG

mybatis:
  #设置Mapper文件的映射
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: sch.hunnu.entity
#  configuration:
#    cache-enabled: true #开启 二级缓存

