server:
  port: 8088
  servlet:
    session:
      timeout: 3600   #servlet session 的会话超时 3600s   
        
spring:
  application:
    name: JavaMailByQQ
   
      
  datasource:
        
        url: jdbc:mysql://127.0.0.1:3306/char
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20 

  thymeleaf:
    #不缓存 及时刷新 ，上线应该设置为true
    cache: false
    #开启MVC视图解析器
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    #编码
    encoding: UTF-8
    #页面编码
    servlet:
      content-type: text/html; charset=utf-8

#打印mybatis 的sql语句
logging:
  level:
    sch.hunnu.dao: DEBUG
    
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: sch.hunnu.entity  # 注意：对应实体类的路径 取上别名 